language: python
sudo: false
python:
  - 2.7

env:
  - TASK=checks
  - TASK=unit

services:
  - mongodb
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/pip/

install:
 - if [[ ${TASK} == 'unit' ]]; then pip install python-coveralls; fi
 - make requirements

script:
  - ./scripts/travis.sh

after_success:
  - if [[ ${TASK} == 'unit' ]]; then coveralls; fi
