language: python
sudo: false
python:
  - 2.7

env:
  - TASK=unit

services:
  - mongodb
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/pip/

install:
 - pip install python-coveralls
 - make requirements

script:
  - ./scripts/travis.sh

after_success:
  - coveralls
