# Used old infrastructure, needed for integration tests:
# http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: true
language: python
python:
  - 2.7

env:
  - TASK=unit
  - TASK=integration

services:
  - mongodb
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/pip/

install:
  - pip install python-coveralls
  - if [ ${TASK} = 'integration' ]; then sudo ./scripts/travis/prepare-integration.sh; fi
  - make requirements

script:
  - ./scripts/travis/build.sh

after_success:
  - coveralls
