# Used old infrastructure, needed for integration tests:
# http://docs.travis-ci.com/user/workers/standard-infrastructure/
sudo: true
language: python
python:
  - 2.7

env:
  - TASK=checks
  - TASK=unit
  - TASK=integration
  - TASK=mistral

matrix:
  fast_finish: true
  allow_failures:
    - env: TASK=mistral

services:
  - mongodb
  - postgresql
  - rabbitmq

cache:
  directories:
    - $HOME/.cache/pip/

install:
  - if [ ${TASK} != 'checks' ]; then pip install python-coveralls; fi
  - make requirements
  - if [ ${TASK} = 'integration' ] || [ ${TASK} = 'mistral' ]; then sudo ./scripts/travis/prepare-integration.sh; fi
  - if [ ${TASK} = 'mistral' ]; then sudo ./scripts/travis/setup-mistral.sh; fi

script:
  - ./scripts/travis/build.sh

after_success:
  - if [ ${TASK} != 'checks' ]; then coveralls; fi
