---
pack: marketing
name: ac_revoke_enterprise_token_packagecloud_stable
description: 'Remove an enterprise token from PackageCloud on webhook from ActiveCampaign'
type:
  ref: standard
  parameters: {}
enabled: true

tags: []

trigger:
  ref: activecampaign.webhook
  type: activecampaign.webhook
  parameters: {}

criteria:
  trigger.action:
    pattern: remove_enterprise_token
    type: eq
  trigger.body["contact[tags]"]:
    pattern: BWCEntTrialLicense
    type: contains

action:
  ref: marketing.revoke_enterprise_license_packagecloud
  parameters:
    repository: enterprise
    user: stackstorm
    token_identifier: '{{trigger.body["contact[email]"]}}'
    ent_token: '{{trigger.body["contact[fields][licensekey]"]}}'


