version: 2
jobs:
  build:
    #working_directory: ~/st2
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: docker/compose:1.14.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: YOLO
          command: echo 'YOLO'
