version: 2
jobs:
  build:
    parallelism: 1
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: ubuntu:trusty
    working_directory: ~/st2
    environment:
      - DISTROS: "trusty xenial el6 el7"
      - ST2_PACKAGES_REPO: https://github.com/StackStorm/st2-packages
      - DEPLOY_PACKAGES: 0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies - should be done as a pre-packed Docker image later
          command: |
            set -x
            apt-get update
            apt-get install -y curl git bash
            curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Download st2-packages repository
          command: |
            set -x
            git clone --depth 1 ${ST2_PACKAGES_REPO} ~/st2-packages
            cd ~/st2-packages
            git checkout ${CIRCLE_BRANCH} || true

      - run:
          name: Pull the dependent build & test Docker images
          command: docker-compose run trusty /bin/true
          working_directory: ~/st2-packages
