version: 2
jobs:
  build:
    parallelism: 1
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: docker/compose:1.14.0
    working_directory: ~/st2
    environment:
      - DISTROS: "trusty xenial el6 el7"
      - ST2_PACKAGES_REPO: https://github.com/StackStorm/st2-packages
      - DEPLOY_PACKAGES: 0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies - this should be done as a pre-packed Docker image later
          command: |
            sudo apt-get install -y git

      - run:
          name: Download st2-packages repository
          command: |
            set -x
            git clone --depth 1 ${ST2_PACKAGES_REPO} ~/st2-packages
            cd ~/st2-packages
            git checkout ${CIRCLE_BRANCH} || true
