swagger: '2.0'

info:
  version: "1.0.0"
  title: StackStorm st2stream API

basePath: /v1

paths:
  /stream:
    get:
      operationId: st2stream.controllers.v1.stream:stream_controller.get_all
      description: |
        Event stream endpoint.
      responses:
        '200':
          description: EventSource compatible stream of events
          examples:
            application/json:
              ref: 'core.local'
              # and stuff
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      faultstring:
        type: string

securityDefinitions:
  X-Auth-Token:
    description: Header representing user's short-lived access token.
    type: apiKey
    name: X-Auth-Token
    in: header
    x-operationId: st2common.util.auth:validate_token
  St2-Api-Key:
    description: Header representing service's long-lived API key.
    type: apiKey
    name: St2-Api-Key
    in: header
    x-operationId: st2common.util.auth:validate_api_key
  x-auth-token:
    description: Query parameter representing user's short-lived access token. Used as a backup authentication strategy for environments where it is impossible to provide a header.
    type: apiKey
    name: x-auth-token
    in: query
    x-operationId: st2common.util.auth:validate_token
  st2-api-key:
    description: Query parameter representing service's long-lived API key. Used as a backup authentication strategy for environments where it is impossible to provide a header.
    type: apiKey
    name: st2-api-key
    in: query
    x-operationId: st2common.util.auth:validate_api_key

security:
  - X-Auth-Token: []
  - St2-Api-Key: []
  - x-auth-token: []
  - st2-api-key: []
